### ISSUE TITLE
Formal equiv diff inside operator

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/synlig#1045]
Test UHDM-integration-tests/tests/OneInside/dut.v
./run_formal_verif.sh test=OneInside_dut.v

sv2v correctly translate this 
assign b = a[2] &
		(a inside {OP_1,
					OP_2,
					OP_3});

into:

assign b = a[2] & |{a == OP_1, a == OP_2, a == OP_3};

And Yosys produces the correct logic.

UHDM models the inside operator correctly. 
The plugin creates an incorrect AST for Yosys, maybe it should create an AST like sv2v

**Comment by kamilrakoczy** [comment]
`OneInside` is now passing formal verification. Closing issue.
