### ISSUE TITLE
Include clang-format CI check 

### ISSUE THREAD

**Issue by hzeller** [chipsalliance/synlig#1933]
Once development is going, it might be worthwhile to add clang-format in this repo.

Simple example in Surelog
https://github.com/chipsalliance/Surelog/blob/master/.clang-format
https://github.com/chipsalliance/Surelog/blob/master/.github/bin/run-clang-format.sh

(Lower priority feature request)

**Comment by kbieganski** [comment]
Yes, we should definitely add it. Probably right after https://github.com/chipsalliance/synlig/pull/1941
