### ISSUE TITLE
Plugin error induces Yosys assert: ERROR: enum item \ADC_CTRL_INTR_STATE already exists

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/synlig#1988]
The following testcase is a frequent error in the plugin/yosys.

**ERROR: enum item \ADC_CTRL_INTR_STATE already exists**

The culprit is that the plugin builds a current_scope that appends twice the imported package content.
The package is first imported at the file level, then again at the module level.
The plugin should keep in any given scope the latest definition of any symbols and not keep 2 or n definition of the same symbol seem through the hierarchy. It should pass only one such symbol to yosys in any given scope.

![Screenshot from 2023-09-18 21-01-37](https://github.com/chipsalliance/synlig/assets/63669492/9722505a-7cea-4d80-83ed-a3d40e8a01f7)

Important note:  you need to build yosys in debug mode to actually get the correct assert shown in the attached picture.
In release build mode, you get a different assert which make no sense:
ERROR: Assert `node->type == AST_STRUCT_ITEM' failed in frontends/ast/simplify.cc:316.

Complete reduced testcase:

```
package adc_ctrl_reg_pkg;
  typedef enum int {
    ADC_CTRL_INTR_STATE,
    ADC_CTRL_INTR_ENABLE
  } adc_ctrl_id_e;
endpackage

import adc_ctrl_reg_pkg::* ;

module M();
  import adc_ctrl_reg_pkg::* ;
endmodule

module top ();
  M m1();
endmodule
```

**Comment by kbieganski** [comment]
Draft fix at #1992
