### ISSUE TITLE
How to build in debug mode?

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/synlig#2045]
I have been mocking around with the respective makefiles, but it would be nice to be able to build everything in debug mode

**Comment by alaindargelas** [comment]
Create a file at the top level: buildconfig.user.mk
With the following content:

CFG_BUILD_TYPE := debug

**Comment by alaindargelas** [comment]
Actually frontends/systemverilog/Build.mk is not sensitive to that.
It would be nice if one did not have to edit manually that file to change -O3 by -g

**Comment by kbieganski** [comment]
#2048 should fix it.

**Comment by alaindargelas** [comment]
Thanks!
