### ISSUE TITLE
Undefined parameter causes segfault

### ISSUE THREAD

**Issue by mole99** [chipsalliance/synlig#2077]
A simple example causing a segfault with the current synlig:

```SystemVerilog
module top #(
    parameter param
);

    test #(
        .param(param)
    ) test_i (
    );

endmodule

module test #(
    parameter param
)();

endmodule
```

Synlig should propably print a warning that `param` in `top` needs a default value.

**Comment by alaindargelas** [comment]
Will issue an error in Surelog

**Comment by alaindargelas** [comment]
Fixed by https://github.com/chipsalliance/Surelog/pull/3914.
Will have to wait that Surelog gets merged to close.

**Comment by kgugala** [comment]
I've bumped Surelog submodule and it now has the required change. I suppose we can close this one

**Comment by mole99** [comment]
Tested and works for me, thanks!
