### ISSUE TITLE
gdb breakpoint aliasing on simplify.cpp 

### ISSUE THREAD

**Issue by alaindargelas** [chipsalliance/synlig#2112]
Both Yosys and the plugin have a file called simplify.cpp,
it is virtually impossible to debug these files as breakpoints gets aliased to the other file.
Set a BP in the Yosys file, and gdb show the yosys_mod/simplify.cpp file when it hits it.

Solution: rename the local files:
simplify_mod.cpp and simplify_mod..h

@kgugala @kbieganski @hzeller, other suggestions?

**Comment by pgielda** [comment]
maybe synlig_simplify.cpp/.h?

**Comment by alaindargelas** [comment]
OK, I'll submit a PR.
