### ISSUE TITLE
`yosys-config` reports incorrect paths in prebuilt binaries

### ISSUE THREAD

**Issue by aWZHY0yQH81uOYvH** [chipsalliance/synlig#2164]
`yosys-config` reports paths that are baked-in at build time. In the prebuilt releases generated on GitHub, all paths are prefixed with `/root/synlig/synlig/out/release`, which makes the `yosys-config` bundled with Synlig nonfunctional unless the user extracts the archive in exactly that path.

[`oss-cad-suite` overcomes this problem by patching `yosys-config`](https://github.com/YosysHQ/oss-cad-suite-build/blob/f41b9ae59c6afe323b41a069da48c3835f0846b0/scripts/package-linux.sh#L248) (replacing the original build path with a path relative to `yosys-config`'s location). Perhaps something similar could be included in Synlig, either in the main build systems (Make/CMake) or at least in the GitHub workflow that generates the prebuilt binaries.

Ideally, this modification would be included in Yosys's build system, but [the way `yosys-config` is currently generated](https://github.com/YosysHQ/yosys/blob/031ad38b5cc2410823089e1990cd68694a4a9bb3/Makefile#L793) makes it quite difficult since external library include paths can't be easily separated from Yosys's own at that point in the Makefile.

**Comment by tgorochowik** [comment]
Sounds good, we just need to make sure the "plugin only" releases are unaffected (we want them to work with external yosys installs)
