### ISSUE TITLE
how to adapt synlig

### ISSUE THREAD

**Issue by AAAsoft9591** [chipsalliance/synlig#2550]
I need to use the synlig plugin to read SystemVerilog files. However, I also require my own custom Yosys 0.13 version. Is there a way to adapt the synlig plugin to work with my custom Yosys 0.13?

/----------------------------------------------------------------------------\
 |                                                                            |
 |  yosys -- Yosys Open SYnthesis Suite                                       |
 |                                                                            |
 |  Copyright (C) 2012 - 2020  Claire Xenia Wolf <claire@yosyshq.com>         |
 |                                                                            |
 |  Permission to use, copy, modify, and/or distribute this software for any  |
 |  purpose with or without fee is hereby granted, provided that the above    |
 |  copyright notice and this permission notice appear in all copies.         |
 |                                                                            |
 |  THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL WARRANTIES  |
 |  WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF          |
 |  MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR   |
 |  ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES    |
 |  WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR PROFITS, WHETHER IN AN     |
 |  ACTION OF CONTRACT, NEGLIGENCE OR OTHER TORTIOUS ACTION, ARISING OUT OF   |
 |  OR IN CONNECTION WITH THE USE OR PERFORMANCE OF THIS SOFTWARE.            |
 |                                                                            |
 \----------------------------------------------------------------------------/

 Yosys 0.13+15 (git sha1 UNKNOWN, gcc 9.4.0-1ubuntu1~20.04.2 -fPIC -Os)

**Comment by tgorochowik** [comment]
Unfortunately there is no easy way to do this, yosys changes quite a lot between releases, supporting even a few recent versions is quite hard, adjusting to such an old release (like 0.13) would probably require a lot of work.

I assume you might already know this if you maintain your custom fork?

You are of course welcome to try, start by checking out the yosys submodule at the release you need and try to compile. Then start resolving all the API changes to make it compile. Once it compiles, we have quite an extensive regression tests suite which you are welcome to use to make sure everything still works as expected after your changes.

In the end it might be easier to port your custom changes to a more recent yosys version.
